// Code generated by mockery v2.43.0. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	models "comixsearch/internal/models"
)

// Fetcher is an autogenerated mock type for the Fetcher type
type Fetcher struct {
	mock.Mock
}

// GetData provides a mock function with given fields: ctx, maxProc, lastId
func (_m *Fetcher) GetData(ctx context.Context, maxProc int, lastId int64) ([]models.Comic, error) {
	ret := _m.Called(ctx, maxProc, lastId)

	if len(ret) == 0 {
		panic("no return value specified for GetData")
	}

	var r0 []models.Comic
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int, int64) ([]models.Comic, error)); ok {
		return rf(ctx, maxProc, lastId)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int, int64) []models.Comic); ok {
		r0 = rf(ctx, maxProc, lastId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Comic)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int, int64) error); ok {
		r1 = rf(ctx, maxProc, lastId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewFetcher creates a new instance of Fetcher. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewFetcher(t interface {
	mock.TestingT
	Cleanup(func())
}) *Fetcher {
	mock := &Fetcher{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
