// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "consumes": [
        "application/json"
    ],
    "produces": [
        "application/json"
    ],
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "Maintainers",
            "url": "https://github.com/AntonShadrinNN/ComixSearch-Application.git",
            "email": "svebo3348@gmail.com"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/search{limit}": {
            "post": {
                "description": "Returns comices based on user input",
                "produces": [
                    "application/json"
                ],
                "summary": "Get comices",
                "parameters": [
                    {
                        "description": "Keywords for comic's search",
                        "name": "keywords",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/httpgin.userRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Comices have been received successfully",
                        "schema": {
                            "$ref": "#/definitions/httpgin.Response"
                        }
                    },
                    "400": {
                        "description": "Invalid parameters",
                        "schema": {
                            "$ref": "#/definitions/httpgin.Response"
                        }
                    },
                    "500": {
                        "description": "Search app receiving caused error",
                        "schema": {
                            "$ref": "#/definitions/httpgin.Response"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "httpgin.Response": {
            "type": "object",
            "properties": {
                "comices": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    },
                    "example": {
                        "earth": "http://xkcd/earth"
                    }
                },
                "error": {}
            }
        },
        "httpgin.userRequest": {
            "type": "object",
            "properties": {
                "keywords": {
                    "type": "string",
                    "example": "earth"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0.0",
	Host:             "localhost:8080",
	BasePath:         "",
	Schemes:          []string{"http"},
	Title:            "Comic search application documentation",
	Description:      "A collection of endpoints available to retrieve the comices for a specific keywords.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
