consumes:
- application/json
definitions:
  httpgin.Response:
    properties:
      comices:
        additionalProperties:
          type: string
        example:
          earth: http://xkcd/earth
        type: object
      error: {}
    type: object
  httpgin.userRequest:
    properties:
      keywords:
        example: earth
        type: string
    type: object
host: localhost:8080
info:
  contact:
    email: svebo3348@gmail.com
    name: Maintainers
    url: https://github.com/AntonShadrinNN/ComixSearch-Application.git
  description: A collection of endpoints available to retrieve the comices for a specific
    keywords.
  title: Comic search application documentation
  version: 1.0.0
paths:
  /search{limit}:
    post:
      description: Returns comices based on user input
      parameters:
      - description: Keywords for comic's search
        in: body
        name: keywords
        required: true
        schema:
          $ref: '#/definitions/httpgin.userRequest'
      produces:
      - application/json
      responses:
        "200":
          description: Comices have been received successfully
          schema:
            $ref: '#/definitions/httpgin.Response'
        "400":
          description: Invalid parameters
          schema:
            $ref: '#/definitions/httpgin.Response'
        "500":
          description: Search app receiving caused error
          schema:
            $ref: '#/definitions/httpgin.Response'
      summary: Get comices
produces:
- application/json
schemes:
- http
swagger: "2.0"
